version: "3.9"
networks:
  bridge_network:
    driver: bridge
services:
  mongo:
    container_name: mongo_99tech_env_local
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=tech99
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Godofwar246357
    ports:
      - "27017:27017"
    networks:
      - bridge_network
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
volumes:
  mongo_data:
  elastic_search_data:
# docker compose -p env_local_my_99tech -f docker-compose.env.local.yaml up -d
# docker compose -p env_local_my_99tech down
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
