version: "3.9"
networks:
  bridge_network:
    driver: bridge
services:
  nginx:
    container_name: nginx_99tech_env_production
    build:
      context: ./stack-fe
      dockerfile: env.production.Dockerfile
    ports:
      - "3004:80"
    volumes:
      - ./nginx/config/default.env.production.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bridge_network
    restart: unless-stopped
  mongo:
    container_name: mongo_99tech_env_production
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=99tech
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Godofwar246357
    ports:
      - "27017:27017"
    networks:
      - bridge_network
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  backend:
    container_name: backend_99tech_env_production
    build:
      context: ./stack-be
      dockerfile: env.production.Dockerfile
    ports:
      - "8004:8000"
    networks:
      - bridge_network
    restart: unless-stopped
volumes:
  mongo_data:
# docker compose -p env_production_my_99tech -f docker-compose.env.production.yaml up -d
# docker compose -p env_production_my_99tech down
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
